version: "3.8"

networks:
  default:
    name: $DEFAULT_NETWORK_NAME
services:
  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    profiles:
      - test
    labels:
      - "traefik.enable=true"
      - "traefik.backend=whoami"
      - "traefik.docker.network=$DEFAULT_NETWORK_NAME"
      # - "traefik.useBindPortIP=true"
      # - "traefik.http.services.dify.loadbalancer.server.port=80"
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
    deploy:
      replicas: 3
