version: "3.8"

networks:
  default:
    name: gatewayz
    external: true

services:
  agent:
    container_name: portainer_agent
    image: portainer/agent:2.20.3-alpine
    restart: unless-stopped
    environment:
      AGENT_CLUSTER_ADDR: $AGENT_DOMAIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
