networks:
  default:
    name: gatewayz
    external: true

services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:1.30.3
    volumes:
      - $VOLUMES_DIR./_data:/data
    restart: unless-stopped
    environment:
      DOMAIN: $DOMAIN
      ADMIN_TOKEN: $ADMIN_TOKEN
