version: "3.8"
networks:
  default:
    name: $COMPOSE_DEFAULT_NETWORK

services:
  mysql-cli:
    image: mariadb:10.6
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      SERVICE_TAGS: $SERVICE_TAGS
      SERVICE_NAME: mysql
    entrypoint:
      - mysql
      - "-hmysql"
      - "-u$MYSQL_USER"
      - "-p$MYSQL_PASSWORD"
      - "--default-character-set=utf8"
