version: "3.8"

networks:
  default:
    name: $COMPOSE_DEFAULT_NETWORK
  gatewayz:
    name: gatewayz
    external: true

services:
  server:
    container_name: portainer_server
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9001:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $VOLUMES_DIR./_data:/data
    networks:
      - default
      - gatewayz

  agent:
    container_name: portainer_agent
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: $AGENT_DOMAIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - default
      - gatewayz
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
