name: Deploy to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      APP_NAME: gatewayz
      APP_NETWORK: gatewayz
      APP_VOLUMES_DIR: /home/${{ secrets.EC2_USERNAME }}/volumes/gatewayz/
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Generate env file from template
      run: envsubst < template.env > .env

    - name: Copy files to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: ".,!node_modules"
        target: "/home/${{ secrets.EC2_USERNAME }}/${{ env.APP_NAME }}"
        strip_components: 0
        overwrite: true
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/${{ secrets.EC2_USERNAME }}/${{ env.APP_NAME }}
          sudo docker-compose down
          sudo docker-compose build --no-cache
          sudo docker-compose up -d 